---
- name: "Verificar que sudo está instalado"
  ansible.builtin.apt:
    cache_valid_time: 3600
    name: "sudo"
    state: "present"
    update_cache: true

# Añadir usuario administrador con bash y privilegios sudo
- name: "Agregar usuario administrador"
  ansible.builtin.user:
      append: true
      groups: "sudo"
      name: "{{ usuarios_administrador }}"
      shell: "/bin/bash"

- name: "Configurar sudo sin contraseña para el administrador"
  ansible.builtin.copy:
      content: "{{ usuario_administrador }}  ALL=(ALL) NOPASSWD: ALL"
      dest: "/etc/sudoers.d/010_{{ usuario_administrador }}_nopasswd"
      mode: 0440
      validate: "/usr/sbin/visudo -cf %s"
